### ISSUE TITLE
Trouble with package virtualbox

### ISSUE THREAD

**Issue by alexzbs** [seba76/virtualbox4dsm#10]
Hello.
I have installed я virtualbox4dsm v.6.0.8-130520 package at my device synology DS412+(cedarview),  OS: DSM 6.2.2-24922 Update 2.
But this package doesn't start. I run it and see load indication for short time but it doesn't start then.
What could be a problem and how can i fix it?
Thank you.

**Comment by seba76** [comment]
In your virtualbox shared folder you should have scripts.log file. It should give you an idea of what is going on. If you can't figure it out add it to the issue here so I can take a look.

**Comment by alexzbs** [comment]
Thank you for your answer! Unfortunately I can't figured out my problem. If you'll help me with it, I'll be grateful! You can find a logfile in attached. 

[scripts.log](https://github.com/seba76/virtualbox4dsm/files/3505496/scripts.log)

**Comment by seba76** [comment]
Can you post content of /etc/vbox/vbox.cfg and output of following commands
` lsmod | grep vbox` and ` ps aux | grep VirtualBox`

**Comment by alexzbs** [comment]
> /etc/vbox/vbox.cfg

No such directory in my device(
lsmod attached
[lsmod_log.txt](https://github.com/seba76/virtualbox4dsm/files/3509024/lsmod_log.txt)

Other files I can't find because I can't find such directory
![image](https://user-images.githubusercontent.com/28780469/63159454-4629a200-c024-11e9-8aed-afafa812dcc1.png)

**Comment by seba76** [comment]
You should run
**lsmod | grep vbox**
and then
**ps aux | grep VirtualBox**
but I guess problem is missing /etc/vbox/vbox.cfg which is required.
I suggest you first uninstall virtualbox package and then install again.

**Comment by alexzbs** [comment]
lsmod | grep vbox
![image](https://user-images.githubusercontent.com/28780469/63167574-5d738a00-c03a-11e9-9f70-418a0c983c50.png)

ps aux | grep VirtualBox
![image](https://user-images.githubusercontent.com/28780469/63167577-606e7a80-c03a-11e9-8648-c1b564832ec8.png)

Should I really REinstall virtualbox?

**Comment by seba76** [comment]
Not reinstall,  you must first uninstall then install.  Config file /etc/vbox/vbox.cfg is absolutely necessary for virtualbox.  Alternatively you can create that file by hand, but uninstall and then install will confirm that there is no problem with package. If it is not working after un/install process then for some reason package is not installing properly on your nas. Here is sample [vbox.cfg](https://github.com/seba76/virtualbox4dsm/blob/master/package/etc/vbox/vbox.cfg)

**Comment by alexzbs** [comment]
I deleted virtualbox4dsm and reInstall it. After installation, I launched it. Log of this operation you can find in attached( scripts.log)

`**** Start at Mon Aug 19 11:27:20 MSK 2019 ****
Starting VirtualBox kernel modules
Loading driver from: /var/packages/virtualbox4dsm/target/drivers/cedarview/3.10.105
vboxdrv loaded successfully
vboxnetflt loaded successfully
vboxnetadp loaded successfully
vboxpci loaded successfully
Starting VirtualBox kernel modules. Done!
Starting VirtualBox web service
stop vm's is not enabled. add  VBOXWEB_USER=vbox in /etc/vbox/vbox.cfg to enable
vbox wol starting
Traceback (most recent call last):
  File "/var/packages/virtualbox4dsm/target/wol/vboxwolservice.py", line 229, in <module>
    svc.start(iniFile)
  File "/var/packages/virtualbox4dsm/target/wol/vboxwolservice.py", line 78, in start
    self.run()
  File "/var/packages/virtualbox4dsm/target/wol/vboxwolservice.py", line 94, in run
    url = self.ConfigSectionMap('Credentials')['url']
  File "/var/packages/virtualbox4dsm/target/wol/vboxwolservice.py", line 62, in ConfigSectionMap
    options = self.Config.options(section)
  File "/usr/lib/python2.7/ConfigParser.py", line 279, in options
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'Credentials'
vbox wol done
**** Start finished at Mon Aug 19 11:27:24 MSK 2019 ****`

Thus the application doesn't start, moreover /etc/vbox/vbox.cfg **doesn't create with installation**

**Comment by seba76** [comment]
That is weird. Well to fix this you can manually create vbox.cfg. Unfortunately creating package for arch that you cant test is not easy, a lot if stuff can go wrong. 
Reason why installation is broken might be found in install log file, try to execute
`cat /var/log/synopkg.log | grep virtualbox4dsm`
as root.

**Comment by alexzbs** [comment]
I created /etc/vbox/vbox.cfg, then queried cat /var/log/synopkg.log | grep virtualbox4dsm , log in attached
[log.txt](https://github.com/seba76/virtualbox4dsm/files/3520193/log.txt)

I started virtualbox4dsm and it doesn't work.
```
**** Start at Tue Aug 20 12:03:29 MSK 2019 ****
Starting VirtualBox kernel modules
Loading driver from: /var/packages/virtualbox4dsm/target/drivers/cedarview/3.10.105
vboxdrv loaded successfully
vboxnetflt loaded successfully
vboxnetadp loaded successfully
vboxpci loaded successfully
Starting VirtualBox kernel modules. Done!
Starting VirtualBox web service
su: user root
 does not exist
Error 0 setting webservice authentication library to null
Starting FAIL!
Starting VirtualBox web service. Done!
vboxinit starting VM's
su: user root
 does not exist
vboxinit starting done
vbox wol starting
Traceback (most recent call last):
  File "/var/packages/virtualbox4dsm/target/wol/vboxwolservice.py", line 229, in <module>
    svc.start(iniFile)
  File "/var/packages/virtualbox4dsm/target/wol/vboxwolservice.py", line 78, in start
    self.run()
  File "/var/packages/virtualbox4dsm/target/wol/vboxwolservice.py", line 94, in run
    url = self.ConfigSectionMap('Credentials')['url']
  File "/var/packages/virtualbox4dsm/target/wol/vboxwolservice.py", line 62, in ConfigSectionMap
    options = self.Config.options(section)
  File "/usr/lib/python2.7/ConfigParser.py", line 279, in options
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'Credentials'
vbox wol done
```

What do you think should I do next?

**Comment by seba76** [comment]
Well this is strange, it looks like install finished successful as far as I see from log file. I forgot to say to create [/etc/vbox/vboxwolservice.ini](https://github.com/seba76/virtualbox4dsm/blob/master/package/etc/vbox/vboxwolservice.ini), that will remove this traceback error. but what is problematic is this 
> su: user root
>  does not exist

what do you get when you execute?
` su - root -s /bin/sh -c '/opt/VirtualBox/VBoxManage list vms'`
and also
`ps aux | grep VirtualBox`

**Comment by alexzbs** [comment]
Thank you for your help!
I've created  /etc/vbox/vboxwolservice.ini. I already have root rights. 

When I executed this
_su - root -s /bin/sh -c '/opt/VirtualBox/VBoxManage list vms'_

got this output
```
root@xxxxx:~# su - root -s /bin/sh -c '/opt/VirtualBox/VBoxManage list vms'
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information availabl                            e (required by /opt/VirtualBox/VBoxManage)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information availabl                            e (required by /opt/VirtualBox/VBoxManage)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information availabl                            e (required by /opt/VirtualBox/VBoxDDU.so)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information availabl                            e (required by /opt/VirtualBox/VBoxRT.so)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information availabl                            e (required by /opt/VirtualBox/VBoxRT.so)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information availabl                            e (required by /opt/VirtualBox/VBoxXPCOM.so)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information availabl                            e (required by /opt/VirtualBox/VBoxXPCOM.so)
```


And after executed this query _ps aux | grep VirtualBox_
Got this
```
/etc/vbox$ ps aux | grep VirtualBox
root      7708  0.0  0.0   9008   660 ?        S    10:47   0:00 grep VirtualBox
```

**Comment by seba76** [comment]
What do you get for output when you execute?
`sudo /var/packages/virtualbox4dsm/target/scripts/vboxweb-service.sh start`

**Comment by alexzbs** [comment]
```
root@xxxxx:~# sudo /var/packages/virtualbox4dsm/target/scripts/vboxweb-service.sh start
Starting VirtualBox web service
 does not exist
Error 0 setting webservice authentication library to null
Starting FAIL!
Starting VirtualBox web service. Done!
```

**Comment by seba76** [comment]
For some reason web service can't start, what do you get after running
`sudo /opt/VirtualBox/vboxwebsrv`

**Comment by alexzbs** [comment]
I got it

```
root@xxxxx:~# sudo /opt/VirtualBox/vboxwebsrv
/opt/VirtualBox/vboxwebsrv: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/vboxwebsrv)
/opt/VirtualBox/vboxwebsrv: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/vboxwebsrv)
/opt/VirtualBox/vboxwebsrv: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxRT.so)
/opt/VirtualBox/vboxwebsrv: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxRT.so)
/opt/VirtualBox/vboxwebsrv: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxXPCOM.so)
/opt/VirtualBox/vboxwebsrv: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxXPCOM.so)
Oracle VM VirtualBox web service Version 6.0.8
(C) 2007-2019 Oracle Corporation
All rights reserved.
00:00:00.017232 main     VirtualBox web service 6.0.8 r130520 linux.amd64 (May 13 2019 16:01:09) release log
00:00:00.017258 main     Log opened 2019-08-22T09:50:55.240462000Z
00:00:00.017263 main     Build Type: release
00:00:00.017282 main     OS Product: Linux
00:00:00.017286 main     OS Release: 3.10.105
00:00:00.017289 main     OS Version: #24922 SMP Wed Jul 3 16:35:48 CST 2019
00:00:00.017396 main     DMI Product Name: GRANITE WELL
00:00:00.017421 main     DMI Product Version: 1.0
00:00:00.017723 main     Host RAM: 3947MB (3.8GB) total, 2226MB (2.1GB) available
00:00:00.017775 main     Executable: /opt/VirtualBox/vboxwebsrv
00:00:00.017778 main     Process ID: 30188
00:00:00.017780 main     Package type: LINUX_64BITS_GENERIC
00:00:00.090025 main     IPC socket path: /tmp/.vbox-root-ipc/ipcd
00:00:00.681957 SQPmp    Socket connection successful: host = default (localhost), port = 18083, master socket = 8
00:00:05.612784 Watchdog Statistics: 0 websessions, 0 references
```

**Comment by seba76** [comment]
Unfortunately I'm out of ideas. Judging on your output web service is working, there is something that is problematic with your setup which prevents starting web service. I don't know if that is specific to your setup or general for cedarview. Without actual box it is impossible for me to debug. 

Btw. after running `sudo /opt/VirtualBox/vboxwebsrv` you should be able to open phpvirtualbox if configuration file for it is correct. What you could do, if phpvbox is working is to modify vboxweb-service.sh where you would replace content of start method with following code 
[start.txt](https://github.com/seba76/virtualbox4dsm/files/3530216/start.txt)

**Comment by seba76** [comment]
Due to inactivity I'm closing this issue.
