### ISSUE TITLE
Correct Package for DS1511+

### ISSUE THREAD

**Issue by Jamyz** [seba76/virtualbox4dsm#12]
Hi.
What is the correct package for old DSM DS1511+ ?
Thanks

**Comment by seba76** [comment]
As i wrote in installation instruction
 

> First you need to find out what arch your Synology NAS belongs to, you can consult [here](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Compatibility_Peripherals/What_kind_of_CPU_does_my_NAS_have).
