### ISSUE TITLE
what is user and passwd

### ISSUE THREAD

**Issue by d9394** [seba76/virtualbox4dsm#13]
My DS-1515+ after install virtualbox4dsm-avoton-6.0.8-130520.spk , and let it started.
then I get and install phpvirtualbox from github, but when I want to modify config.php in phpvirtualbox :
/* Username / Password for system user that runs VirtualBox */
var $username = 'vbox';
var $password = 'pass';
So , what is the correct value is 'username' and 'password' ?

**Comment by seba76** [comment]
Those values should be filled during installation. Why do wish to change them manually?

**Comment by d9394** [comment]
I had solved, that is not the problem of username and password, the problem is on my DSM , I forget config nginx for the folder phpvirtualbox with php fastcgi.
