### ISSUE TITLE
Question about spk version 5.2.16 x86-64

### ISSUE THREAD

**Issue by shinn32** [seba76/virtualbox4dsm#16]
Cheers. Does the versions 5.2.16 for Synology DSM 6.2 x64 support AMD based box?I successfully installed it on my AMD a4-5000 based box but i can't even start it.My DSM version is 6.2 23739.Thanks!

**Comment by seba76** [comment]
I don't think so. Build involves compiling drivers for Virtualbox, which I guess depend on CPU type. Check what do you get in log files, that might give a clue what went wrong.

**Comment by shinn32** [comment]
em....where can I get the log files？

**Comment by seba76** [comment]
I'we created wiki page [Troubleshoot](https://github.com/seba76/virtualbox4dsm/wiki/Troubleshooting) with list of some of the files  that can help to see what is going on.

**Comment by blacksushi76** [comment]
Which version i have to use for DS712+ the cpu is an intel atom D425 pineview i have last kernel 3.10.105.
thanks

**Comment by seba76** [comment]
> 
> 
> Which version i have to use for DS712+ the cpu is an intel atom D425 pineview i have last kernel 3.10.105.
> thanks

You NAS is not supported.
