### ISSUE TITLE
Issue login web and spk virutalbox on Synology 218+

### ISSUE THREAD

**Issue by DrDuszek** [seba76/virtualbox4dsm#17]
have issue web this installed work then and virtualbox for dim 6.2 no work

https://monosnap.com/file/3R98QvYupwiiZDilLrXVBX7NkQxXZK
https://monosnap.com/file/JUtm1d7hhyX6IVfMuoCN6MpyuiFvup

https://monosnap.com/file/YNyd6Zs6A4Gxz8vT847f1QeMoUZnNp

Exception Object
(
    [message:protected] => Unable to parse URL ()
    [string:Exception:private] => 
    [code:protected] => 64
    [file:protected] => /var/services/web/phpvirtualbox4dsm/endpoints/api.php
    [line:protected] => 134
    [trace:Exception:private] => Array
        (
        )

    [previous:Exception:private] => 
)

**Comment by seba76** [comment]
The issue you are having is not with phpVirtualbox package. Problem is you don't have Virtualbox installed. Your NAS is Apollolake arch while you where trying to install package for Bromolow. I don't speak polish language but I guess message you get is about package not supported or something like that. In any case that architecture is not supported by my packages.
