### ISSUE TITLE
Updated SPK for Braswell architecture (DS916+)

### ISSUE THREAD

**Issue by Joeri87** [seba76/virtualbox4dsm#18]
Dear Seba76,

Thank you for your work.
I really hope to update the package you worked on. Unfortunately, the Braswell architecture is not inculded in your latest release.

Is there any possibility it can be added? I'm sorry I'm not skilled enough to compile it myself.

Kind regards and many thanks in advance!

Joeri

**Comment by seba76** [comment]
My free time is very limited so I can't add it my self, but if someone is willing to add it I will accept pull requests.
