### ISSUE TITLE
Cannot see Volume2 of my DSM

### ISSUE THREAD

**Issue by Oxtie** [seba76/virtualbox4dsm#19]
Vbox is installed on second physical HDD (VOLUME2) but phpvirtualbox's UI only shows Volume1 (doesn't even allow manual input of path which worked for .vdi creation  atleast)

my first HDD failed with data loss 😢  now, DSM  and packages are on second bay HDD slot AND has Volume2/VirtualBox

**Comment by seba76** [comment]
UI questions are often related to phpVirtualbox and it's official website is the place to look for answers. I just made a package and installer for DSM. For your problem this is the case also. Take a look in the config.php file, in there you will find:
>// Restrict locations / folders
>#var $browserRestrictFolders = array('D:\\','C:\\Users\\Ian'); // Or something like array('/home/vbox','/var/ISOs')
>var $browserRestrictFolders = array('/volume1');

adjust it to include paths you need.
