### ISSUE TITLE
DSM 412+ / 64 bit

### ISSUE THREAD

**Issue by thomasmay** [seba76/virtualbox4dsm#22]
Hi,

thank you for your great work. I could install the latest versions of VirtualBox4DSM and PHPVirtualBox on a DS 412+ and run VMs in 32 bit mode.

VirtualBox doesn't offer me Linux / 64 bit for new VMs, though. The processor of the DS 412+ (Atom D2700 cedarview) is supposed to be 64 bit, and this is also what uname -a shows me:
Linux diskstation 3.10.105 #25556 SMP Thu Mar 18 12:51:35 CST 2021 x86_64 GNU/Linux synology_cedarview_412+

So is there something I could have misconfigured that now prevents creating 64 bit VMs?

Thanks
Thomas

**Comment by seba76** [comment]
According to [Intel](https://ark.intel.com/content/www/us/en/ark/products/59683/intel-atom-processor-d2700-1m-cache-2-13-ghz.html) you CPU doesn't have VT-x which is required for 64bit emulation, if I recall correctly.

**Comment by thomasmay** [comment]
I see, thank you
