### ISSUE TITLE
Not working on 6.2.1 DSM

### ISSUE THREAD

**Issue by dacorn** [seba76/virtualbox4dsm#4]
Will you be updating this for the new DSM versions?

Thanks!

**Comment by seba76** [comment]
Latest release is currently running on bromolow DS3615xs v6.2.1, please provide more info about what you tried and what is not working, package, syno box type version etc.

**Comment by dacorn** [comment]
HI,

I am running 6.2.1- 23824 on a Model DS1513+.

The error says “This package is not supported on the platform of DiskStation or is incompatible with the current DSM version.”

Does this help?

Cheers,
Dave

**Comment by seba76** [comment]
It looks like your NAS has atom processor which is not supported. Which package did you use and what is the output of 'uname -a'?

**Comment by seba76** [comment]
Since there is no more info I'm closing this issue.
