### ISSUE TITLE
cannot compile 6.2 braswell

### ISSUE THREAD

**Issue by joostieke** [seba76/virtualbox4dsm#8]
Hello, many thanks for the good work but it doesn 't really work at my side. I tried both on Synology DS716+2 (DSM 6.2), then Ubuntu and now on Fedora but I don 't succeed. This is what I do... on my Fedora 30 as root.
mkdir toolkit
cd toolkit/
git clone https://github.com/SynologyOpenSource/pkgscripts-ng.git
./pkgscripts-ng/EnvDeploy -v 6.2 -p braswell
mkdir source
cd source
git clone https://github.com/seba76/virtualbox4dsm.git
cd virtualbox4dsm

And until here all seems OK.

[root@myserver virtualbox4dsm]# ./config.sh prep
1) DSM 6.1 (15152)
**2) DSM 6.2 (22259)**
3) Quit
Please select DSM varsion: 2
1) bromolow
2) x64
3) broadwell
**4) braswell**
5) cedarview
6) avoton
7) Quit
Please select platform: 4
Setting kernel download link for branch 22259, braswell platform
Kernel exists, delete to download again.
Generating .config
Update version in INFO.sh
Update version in vbox.cfg
Ready to exec:
         'sudo ./pkgscripts-ng/PkgCreate.py --print-log -I -S -p braswell -v 6.2 linux-3.10.x'
         'sudo ./pkgscripts-ng/PkgCreate.py --print-log -c -I -S -p braswell -v 6.2 -x0 -c virtualbox4dsm'

And then I try the kernel build from inside the toolkit folder.
cd ../..
**./pkgscripts-ng/PkgCreate.py --print-log -I -S -p braswell -v 6.2 linux-3.10.x**

It starts... but after some minutes it fails, I don 't know why. This is the error log.

_Set cache size limit to 3.0 Gbytes
Statistics cleared
[INFO] projectList="linux-3.10.x"
[INFO] Start to build linux-3.10.x.
[SCRIPT] build script: //source/linux-3.10.x/SynoBuildConf/build
[INFO] ======= Run build script =======
cp: cannot stat '/lnxscripts/config/signing_key': No such file or directory
cp: cannot stat '/lnxscripts/config/trusted_certificates': No such file or directory
cp: cannot stat '/lnxscripts/config/untrusted_certificates': No such file or directory
/source/linux-3.10.x/crypto/ocf/ep80579/Makefile:75: ICP_ROOT is undefined. Please set the path to EP80579 release package directory "-> setenv ICP_ROOT <path>"
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf --oldconfig Kconfig
#
# configuration written to .config
#
=====Build Synology Linux kernel 3.10.x =====
In file included from scripts/sortextable.c:161:0:
scripts/sortextable.c: In function 'main':
scripts/sortextable.h:158:3: warning: 'relocs_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
   memset(relocs, 0, relocs_size);
   ^
scripts/sortextable.h:104:6: note: 'relocs_size' was declared here
  int relocs_size;
      ^
In file included from scripts/sortextable.c:159:0:
scripts/sortextable.h:158:3: warning: 'relocs_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
   memset(relocs, 0, relocs_size);
   ^
scripts/sortextable.h:104:6: note: 'relocs_size' was declared here
  int relocs_size;
      ^
In file included from include/linux/device.h:27:0,
                 from include/linux/node.h:17,
                 from include/linux/cpu.h:5,
                 from kernel/events/core.c:14:
kernel/events/core.c: In function 'perf_duration_warn':
include/linux/ratelimit.h:22:9: warning: format '%lld' expects argument of type 'long long int', but argument 3 has type 'int' [-Wformat=]
  struct ratelimit_state name = {     \
         ^
include/linux/printk.h:309:9: note: in expansion of macro 'DEFINE_RATELIMIT_STATE'
  static DEFINE_RATELIMIT_STATE(_rs,    \
         ^
kernel/events/core.c:239:2: note: in expansion of macro 'printk_ratelimited'
  printk_ratelimited(KERN_WARNING
  ^
fs/namespace.c: In function 'SyS_mount':
fs/namespace.c:2278:8: warning: 'kernel_dev' may be used uninitialized in this function [-Wmaybe-uninitialized]
  ret = do_mount(kernel_dev, kernel_dir->name, kernel_type, flags,
        ^
fs/namespace.c:2257:8: note: 'kernel_dev' was declared here
  char *kernel_dev;
        ^
fs/namespace.c:2278:8: warning: 'kernel_type' may be used uninitialized in this function [-Wmaybe-uninitialized]
  ret = do_mount(kernel_dev, kernel_dir->name, kernel_type, flags,
        ^
fs/namespace.c:2255:8: note: 'kernel_type' was declared here
  char *kernel_type;
        ^
make[1]: *** No rule to make target 'signing_key', needed by 'signing_key.x509'.  Stop.
make[1]: *** Waiting for unfinished jobs....
Makefile:800: recipe for target 'kernel' failed
make: *** [kernel] Error 2
make: *** Waiting for unfinished jobs....
security/apparmor/lsm.c:835:16: warning: initialization from incompatible pointer type
  .sb_mount =   apparmor_sb_mount,
                ^
security/apparmor/lsm.c:835:16: warning: (near initialization for 'apparmor_ops.sb_mount')
fs/btrfs/inode.c: In function 'btrfs_read_locked_inode':
fs/btrfs/inode.c:3349:1: warning: label 'cache_acl' defined but not used [-Wunused-label]
 cache_acl:
 ^
  GEN     fs/aufs/conf.str
fs/btrfs/ordered-data.c: In function 'btrfs_start_ordered_extent':
fs/btrfs/ordered-data.c:653:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  u64 start = entry->file_offset;
  ^
fs/cifs/sess.c:694:1: warning: 'sess_auth_lanman' defined but not used [-Wunused-function]
 sess_auth_lanman(struct sess_data *sess_data)
 ^
fs/cifs/sess.c:1041:1: warning: 'sess_auth_kerberos' defined but not used [-Wunused-function]
 sess_auth_kerberos(struct sess_data *sess_data)
 ^
fs/ecryptfs/mmap.c: In function 'ecryptfs_aggregate_write_end':
fs/ecryptfs/mmap.c:474:15: warning: unused variable 'lower_file' [-Wunused-variable]
  struct file *lower_file = ecryptfs_inode_to_private(ecryptfs_inode)->lower_file;
               ^
In file included from fs/btrfs/xattr_syno.c:8:0:
fs/btrfs/xattr.h:21:8: warning: 'struct btrfs_trans_handle' declared inside parameter list
        const void *value, size_t size, int flags);
        ^
fs/btrfs/xattr.h:21:8: warning: its scope is only this definition or declaration, which is probably not what you want
fs/btrfs/xattr.h:30:23: warning: 'struct btrfs_trans_handle' declared inside parameter list
          const struct qstr *qstr);
                       ^
Error! /source/linux-3.10.x/arch/x86_64/boot/bzImage does not exist!

[Error] Build project fail!

Time cost: 00:00:52 [Build-->linux-3.10.x]
[INFO] Build linux-3.10.x finished!

----------------- Time cost statistics -----------------
Time cost: 00:00:52 [Build-->linux-3.10.x]

########################################################
      Error(s) occurred on project "linux-3.10.x"
########################################################
1 projects, 1 failed.

[Error] Check [/logs/error.build] for fixing errors.

_

Regards,
Joost

**Comment by seba76** [comment]
That is OK. Point of this line is to prep kernel for building VirtualBox. I think Synology is not giving complete kernel code but it is good enough for building modules. Simply ignore this error and continue with building VirtualBox package.

**Comment by joostieke** [comment]
Yes it works, upgraded from 5.2.20 to 6.0.8, all VM's are running again with updated Guest Additions!

Good idea to take a backup of this one **/root/.config/VirtualBox/VirtualBox.xml** before starting, as my VM's are running on /volume1USB (ssd) instead of volume1 (sata raid) and all settings get lost during update.

Many thanks Seba!

Regards,
Joost

**Comment by seba76** [comment]
Glad it worked. I'm closing this issue.
