### ISSUE TITLE
Rename udev rule file

### ISSUE THREAD

**Issue by seba76** [seba76/virtualbox4dsm#9]
It could be that on some models udev is not picking up rules, to fix this rename file so it includes prefix number.

Thanks at first for creating the SPK's :-) !!!!!

Maybe at Line 114 in the installer script the file has to be renamed 50-virtualbox.rules. Otherwise it isn't executed by udevadm. Tested at DS1515+

_Originally posted by @ghost in https://github.com/seba76/virtualbox4dsm/issues/6#issuecomment-520168779_

**Comment by morettty** [comment]
> Es posible que en algunos modelos udev no esté recogiendo reglas, para corregir este archivo de cambio de nombre para que incluya el número de prefijo.
> 
> Gracias al principio por crear los SPK :-) !!!!!
> 
> Tal vez en la línea 114 en la secuencia de comandos del instalador, el archivo debe renombrarse 50-virtualbox.rules. De lo contrario, no se ejecuta por udevadm. Probado en DS1515 +
> 
> _Publicado originalmente por @ghost en el n [. ° 6 (comentario)](https://github.com/seba76/virtualbox4dsm/issues/6#issuecomment-520168779)_

Hi, thanks for the comment.
Could you tell me how to do it? I'm a newbie
